language: php

matrix:
  include:
    - php: 5.5
      env: SYMFONY_VERSION=2.5.*
    - php: 5.5
      env: SYMFONY_VERSION=2.7.*
    - php: 5.5
      env: SYMFONY_VERSION=2.8.*

env:
  global:
    - SYMFONY_VERSION=""

before_install:
  - >
    if [ "SYMFONY_VERSION" != "" ]; then
      composer require --dev --no-update symfony/framework-bundle "$SYMFONY_VERSION" &&
      composer require --dev --no-update symfony/console "$SYMFONY_VERSION" &&
      composer require --dev --no-update symfony/validator "$SYMFONY_VERSION" &&
      composer require --dev --no-update symfony/form "$SYMFONY_VERSION" &&
      composer require --dev --no-update symfony/yaml "$SYMFONY_VERSION" &&
      composer require --dev --no-update symfony/finder "$SYMFONY_VERSION"
    fi

install:
  - composer update --prefer-source

script:
  - vendor/bin/php-cs-fixer fix -v --diff --dry-run
  - vendor/bin/behat --tags=~symfony27
  - >
    if [ "SYMFONY_VERSION" == "2.7.*" ] || [ "SYMFONY_VERSION" == "2.8.*" ]; then
      vendor/bin/behat --tags=symfony27
    fi

notifications:
  email: matthiasnoback@gmail.com

sudo: false
