language: php

php:
    - 5.5
    - 5.6
    - 7.0
    - hhvm

matrix:
  allow_failures:
    - php: hhvm
  include:
    - php: 5.5
      env: SYMFONY_VERSION=2.8.*
    - php: 5.5
      env: SYMFONY_VERSION=3.0.*

env:
  global:
    - SYMFONY_VERSION=""

before_install:
  - >
    if [ "$SYMFONY_VERSION" != "" ]; then
      composer require --dev --no-update symfony/framework-bundle "$SYMFONY_VERSION" &&
      composer require --dev --no-update symfony/console "$SYMFONY_VERSION" &&
      composer require --dev --no-update symfony/validator "$SYMFONY_VERSION" &&
      composer require --dev --no-update symfony/form "$SYMFONY_VERSION" &&
      composer require --dev --no-update symfony/yaml "$SYMFONY_VERSION" &&
      composer require --dev --no-update symfony/finder "$SYMFONY_VERSION"
    fi

install:
  - composer update --prefer-dist

script:
  - vendor/bin/php-cs-fixer fix -v --diff --dry-run
  - vendor/bin/behat

notifications:
  email: matthiasnoback@gmail.com

sudo: false
