parameters:
    matthias_symfony_console_form.cache_directory: %kernel.cache_dir%/matthias_symfony_console_form

services:
    matthias_symfony_console_form.form_question_helper:
        class: Matthias\SymfonyConsoleForm\Console\Helper\FormQuestionHelper
        arguments:
            - @matthias_symfony_console_form.console_form_factory
            - @matthias_symfony_console_form.delegating_interactor
        tags:
            - { name: console_helper }

    matthias_symfony_console_form.input_definition_factory:
        class: Matthias\SymfonyConsoleForm\Console\Input\FormBasedInputDefinitionFactory
        arguments:
            - @form.factory
            - %matthias_symfony_console_form.cache_directory%
            - %kernel.debug%

    matthias_symfony_console_form.text_transformer:
        class: Matthias\SymfonyConsoleForm\Bridge\Transformer\TextTransformer
        tags:
            - { name: form_to_question_transformer, form_type: text }

    matthias_symfony_console_form.password_transformer:
        class: Matthias\SymfonyConsoleForm\Bridge\Transformer\PasswordTransformer
        tags:
            - { name: form_to_question_transformer, form_type: password }

    matthias_symfony_console_form.choice_transformer:
        class: Matthias\SymfonyConsoleForm\Bridge\Transformer\ChoiceTransformer
        tags:
            - { name: form_to_question_transformer, form_type: choice }
            - { name: form_to_question_transformer, form_type: country }

    matthias_symfony_console_form.delegating_interactor:
        class: Matthias\SymfonyConsoleForm\Bridge\Interaction\DelegatingInteractor
        calls:
            # more specific interactors (by form type acenstry) should be higher in this list
            - [addInteractor, [@matthias_symfony_console_form.non_interactive_root_interactor]]
            - [addInteractor, [@matthias_symfony_console_form.collection_interactor]]
            - [addInteractor, [@matthias_symfony_console_form.compound_interactor]]
            - [addInteractor, [@matthias_symfony_console_form.field_interactor]]

    matthias_symfony_console_form.compound_interactor:
        class: Matthias\SymfonyConsoleForm\Bridge\Interaction\CompoundInteractor
        arguments:
            - @matthias_symfony_console_form.delegating_interactor

    matthias_symfony_console_form.non_interactive_root_interactor:
        class: Matthias\SymfonyConsoleForm\Bridge\Interaction\NonInteractiveRootInteractor
        arguments:
            - @matthias_symfony_console_form.delegating_interactor

    matthias_symfony_console_form.collection_interactor:
        class: Matthias\SymfonyConsoleForm\Bridge\Interaction\CollectionInteractor
        arguments:
            - @matthias_symfony_console_form.delegating_interactor

    matthias_symfony_console_form.field_interactor:
        class: Matthias\SymfonyConsoleForm\Bridge\Interaction\FieldInteractor
        arguments:
            - @matthias_symfony_console.transformer_resolver

    matthias_symfony_console.transformer_resolver:
        class: Matthias\SymfonyConsoleForm\Bridge\Transformer\TypeAncestryBasedTransformerResolver

    matthias_symfony_console_form.handle_form_based_command_event_listener:
        class: Matthias\SymfonyConsoleForm\Console\EventListener\HandleFormBasedCommandEventListener
        arguments:
            - @matthias_symfony_console_form.form_question_helper
        tags:
            - { name: kernel.event_listener, event: console.command, method: onConsoleCommand, priority: 200 }

    matthias_symfony_console_form.set_input_definition_of_form_based_command_event_listener:
        class: Matthias\SymfonyConsoleForm\Console\EventListener\SetInputDefinitionOfFormBasedCommandEventListener
        arguments:
            - @matthias_symfony_console_form.input_definition_factory
        tags:
            - { name: kernel.event_listener, event: console.command, method: onConsoleCommand, priority: 2000 }

    matthias_symfony_console_form.console_form_type_extension:
        class: Matthias\SymfonyConsoleForm\Form\ConsoleFormTypeExtension
        tags:
            - { name: form.type_extension, alias: form }

    matthias_symfony_console_form.console_form_factory:
        class: Matthias\SymfonyConsoleForm\Bridge\FormFactory\ConsoleFormWithDefaultValuesFactory
        arguments:
            - @form.factory
